spring:
  application:
    name: booksapp
  datasource:
    url: jdbc:postgresql://54.227.192.20:80/books #temos que atualizar o IP toda vez que a instância da EC2 subir!
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none  #none -> não cria o banco; update -> cria e mantem o banco baseado no modelo de classes
    show-sql: true
    properties:
      hibernate:
        format_sql: true
